// Permission codes for all modules
// Used throughout the application for permission checks

export const PERMISSION_CODES = {
  // Masters
  UNIT_CREATION: 'UNIT_CREATION',
  COLOR_CREATION: 'COLOR_CREATION',
  SIZE_CREATION: 'SIZE_CREATION',
  MODEL_CREATION: 'MODEL_CREATION',
  SALESMAN_CREATION: 'SALESMAN_CREATION',
  COMPANY_CREATION: 'COMPANY_CREATION',
  USER_CREATION: 'USER_CREATION',
  DESIGN_CREATION: 'DESIGN_CREATION',
  SCRAP_CREATION: 'SCRAP_CREATION',
  BRAND_CREATION: 'BRAND_CREATION',
  CATEGORY_CREATION: 'CATEGORY_CREATION',
  PRODUCT_CREATION: 'PRODUCT_CREATION',
  STATE_CREATION: 'STATE_CREATION',
  ITEM_CREATION: 'ITEM_CREATION',
  ITEM_GRPCREATION: 'ITEM_GRPCREATION',
  LED_GRPCREATION: 'LED_GRPCREATION',
  LEDGER_CREATION: 'LEDGER_CREATION',

  // Transactions
  SALES_INVOICE: 'SALES_INVOICE',
  SALES_RETURN: 'SALES_RETURN',
  PURCHASE_INVOICE: 'PURCHASE_INVOICE',
  PURCHASE_RETURN: 'PURCHASE_RETURN',
  SCRAP_RATE_FIX: 'SCRAP_RATE_FIX',
  SCRAP_PROCUREMENT: 'SCRAP_PROCUREMENT',
  TENDER: 'TENDER',
  BILL_COLLECTOR: 'BILL_COLLECTOR',
  PAYMENT_VOUCHER: 'PAYMENT_VOUCHER',
  RECEIPT_VOUCHER: 'RECEIPT_VOUCHER',

  // Reports
  SALES_REPORT: 'SALES_REPORT',
  STOCK_REPORT: 'STOCK_REPORT',
  PURCHASE_REPORT: 'PURCHASE_REPORT',
  LEDGER_REPORT: 'LEDGER_REPORT',
  TRIAL_BALANCE: 'TRIAL_BALANCE',
  PROFIT_LOSS: 'PROFIT_LOSS',
  BALANCE_SHEET: 'BALANCE_SHEET',
  CASH_FLOW: 'CASH_FLOW',
  STOCK_SUMMARY: 'STOCK_SUMMARY',
  CUSTOMER_STATEMENT: 'CUSTOMER_STATEMENT',
  SUPPLIER_STATEMENT: 'SUPPLIER_STATEMENT',
  TAX_REPORT: 'TAX_REPORT',
  AUDIT_REPORT: 'AUDIT_REPORT',
};
